name: "Auto Assign"
on:
  - pull_request

jobs:
  assign_reviewer:
    runs-on: ubuntu-latest
    steps:
    - name: Generate token
      uses: tibdex/github-app-token@v1
      id: generate-token
      with:
        app_id: ${{ secrets.BOT_APP_ID }}
        private_key: ${{ secrets.BOT_PRIVATE_KEY }}

    - uses: shufo/auto-assign-reviewer-by-files@v1.1.1
      with:
        config: '.github/auto-assign.yml'
        token: ${{ steps.generate-token.outputs.token }}
