name: Pull and push strings via Transifex
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  transifex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Push and pull strings
        uses: ScratchAddons/l10n-script@main
        env:
          TX_TOKEN: ${{ secrets.TX_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
